/*
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package saasgrids;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import saasgrids.Lead;

/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-23T20:00:45.747+05:30")
public class InlineResponse2001 {
  @SerializedName("leads")
  private List<Lead> leads = null;

  public InlineResponse2001 leads(List<Lead> leads) {
    this.leads = leads;
    return this;
  }

  public InlineResponse2001 addLeadsItem(Lead leadsItem) {
    if (this.leads == null) {
      this.leads = new ArrayList<Lead>();
    }
    this.leads.add(leadsItem);
    return this;
  }

   /**
   * Get leads
   * @return leads
  **/
  @ApiModelProperty(value = "")
  public List<Lead> getLeads() {
    return leads;
  }

  public void setLeads(List<Lead> leads) {
    this.leads = leads;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.leads, inlineResponse2001.leads);
  }

  @Override
  public int hashCode() {
    return Objects.hash(leads);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    leads: ").append(toIndentedString(leads)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

