/*
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package saasgrids;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import saasgrids.Contact;

/**
 * InlineResponse2004
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-23T10:40:37.504+05:30")
public class InlineResponse2004 {
  @SerializedName("contacts")
  private List<Contact> contacts = null;

  @SerializedName("skip")
  private String skip = null;

  @SerializedName("more_data")
  private Boolean moreData = null;

  public InlineResponse2004 contacts(List<Contact> contacts) {
    this.contacts = contacts;
    return this;
  }

  public InlineResponse2004 addContactsItem(Contact contactsItem) {
    if (this.contacts == null) {
      this.contacts = new ArrayList<Contact>();
    }
    this.contacts.add(contactsItem);
    return this;
  }

   /**
   * Get contacts
   * @return contacts
  **/
  @ApiModelProperty(value = "")
  public List<Contact> getContacts() {
    return contacts;
  }

  public void setContacts(List<Contact> contacts) {
    this.contacts = contacts;
  }

  public InlineResponse2004 skip(String skip) {
    this.skip = skip;
    return this;
  }

   /**
   * Get skip
   * @return skip
  **/
  @ApiModelProperty(value = "")
  public String getSkip() {
    return skip;
  }

  public void setSkip(String skip) {
    this.skip = skip;
  }

  public InlineResponse2004 moreData(Boolean moreData) {
    this.moreData = moreData;
    return this;
  }

   /**
   * Get moreData
   * @return moreData
  **/
  @ApiModelProperty(value = "")
  public Boolean getMoreData() {
    return moreData;
  }

  public void setMoreData(Boolean moreData) {
    this.moreData = moreData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return Objects.equals(this.contacts, inlineResponse2004.contacts) &&
        Objects.equals(this.skip, inlineResponse2004.skip) &&
        Objects.equals(this.moreData, inlineResponse2004.moreData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contacts, skip, moreData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
    sb.append("    skip: ").append(toIndentedString(skip)).append("\n");
    sb.append("    moreData: ").append(toIndentedString(moreData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

