/*
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package saasgrids;

import crms.ApiException;
import saasgrids.Account;
import saasgrids.InlineResponse2002;
import saasgrids.InlineResponse2005;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
@Ignore
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    
    /**
     * Creates a new account
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountTest() throws ApiException {
        String userId = null;
        Account body = null;
        api.createAccount(userId, body);

        // TODO: test validations
    }
    
    /**
     * Delete account by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAccountByIdTest() throws ApiException {
        String userId = null;
        api.deleteAccountById(userId);

        // TODO: test validations
    }
    
    /**
     * Get account by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountByIdTest() throws ApiException {
        String userId = null;
        String accountId = null;
        Account response = api.getAccountById(userId, accountId);

        // TODO: test validations
    }
    
    /**
     * Get all account filters
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountFiltersTest() throws ApiException {
        String userId = null;
        InlineResponse2002 response = api.getAccountFilters(userId);

        // TODO: test validations
    }
    
    /**
     * Get all accounts by filter
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountsByFilterTest() throws ApiException {
        String userId = null;
        String filterId = null;
        InlineResponse2005 response = api.getAccountsByFilter(userId, filterId);

        // TODO: test validations
    }
    
    /**
     * Get all accounts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllAccountsTest() throws ApiException {
        String userId = null;
        String email = null;
        InlineResponse2005 response = api.getAllAccounts(userId, email);

        // TODO: test validations
    }
    
    /**
     * Update account by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAccountByIdTest() throws ApiException {
        String userId = null;
        Account body = null;
        api.updateAccountById(userId, body);

        // TODO: test validations
    }
    
}
