/*
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package saasgrids;

import crms.ApiException;
import saasgrids.Appointment;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppointmentsApi
 */
@Ignore
public class AppointmentsApiTest {

    private final AppointmentsApi api = new AppointmentsApi();

    
    /**
     * Creates a new appointment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAppointmentTest() throws ApiException {
        String userId = null;
        Appointment body = null;
        api.createAppointment(userId, body);

        // TODO: test validations
    }
    
    /**
     * Delete appointments by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAppointmentsByIdTest() throws ApiException {
        String userId = null;
        api.deleteAppointmentsById(userId);

        // TODO: test validations
    }
    
    /**
     * Get all appointments
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllAppointmentsTest() throws ApiException {
        String userId = null;
        String email = null;
        List<Appointment> response = api.getAllAppointments(userId, email);

        // TODO: test validations
    }
    
    /**
     * Get appointment by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAppointmentByIdTest() throws ApiException {
        String userId = null;
        String appointmentId = null;
        Appointment response = api.getAppointmentById(userId, appointmentId);

        // TODO: test validations
    }
    
    /**
     * Update appointment by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAppointmentByIdTest() throws ApiException {
        String userId = null;
        Appointment body = null;
        api.updateAppointmentById(userId, body);

        // TODO: test validations
    }
    
}
