/*
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package saasgrids;

import crms.ApiException;
import saasgrids.Deal;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DealsApi
 */
@Ignore
public class DealsApiTest {

    private final DealsApi api = new DealsApi();

    
    /**
     * Creates a new deals
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDealsTest() throws ApiException {
        String userId = null;
        Deal body = null;
        api.createDeals(userId, body);

        // TODO: test validations
    }
    
    /**
     * Delete deal by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDealByIdTest() throws ApiException {
        String userId = null;
        api.deleteDealById(userId);

        // TODO: test validations
    }
    
    /**
     * Get all deal
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllDealTest() throws ApiException {
        String userId = null;
        String email = null;
        List<Deal> response = api.getAllDeal(userId, email);

        // TODO: test validations
    }
    
    /**
     * Get deal by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDealByIdTest() throws ApiException {
        String userId = null;
        String dealId = null;
        Deal response = api.getDealById(userId, dealId);

        // TODO: test validations
    }
    
    /**
     * Update deal by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDealByIdTest() throws ApiException {
        String userId = null;
        Deal body = null;
        api.updateDealById(userId, body);

        // TODO: test validations
    }
    
}
