/*
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package saasgrids;

import crms.ApiException;
import saasgrids.Task;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TasksApi
 */
@Ignore
public class TasksApiTest {

    private final TasksApi api = new TasksApi();

    
    /**
     * Creates a new task
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTaskTest() throws ApiException {
        String userId = null;
        Task body = null;
        api.createTask(userId, body);

        // TODO: test validations
    }
    
    /**
     * Delete task by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTaskByIdTest() throws ApiException {
        String userId = null;
        api.deleteTaskById(userId);

        // TODO: test validations
    }
    
    /**
     * Get all tasks
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllTasksTest() throws ApiException {
        String userId = null;
        String email = null;
        List<Task> response = api.getAllTasks(userId, email);

        // TODO: test validations
    }
    
    /**
     * Get task by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTaskByIdTest() throws ApiException {
        String userId = null;
        String taskId = null;
        Task response = api.getTaskById(userId, taskId);

        // TODO: test validations
    }
    
    /**
     * Update task by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTaskByIdTest() throws ApiException {
        String userId = null;
        Task body = null;
        api.updateTaskById(userId, body);

        // TODO: test validations
    }
    
}
